// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown': string;
  'dropdown__image': string;
  'menu': string;
  'menu__image': string;
  'menu__item': string;
  'menu__item--first': string;
  'menu__item--last': string;
}
export const cssExports: CssExports;
export default cssExports;
