// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check__img': string;
  'no': string;
  'visited_before': string;
  'visited_before__title': string;
  'yes': string;
}
export const cssExports: CssExports;
export default cssExports;
