// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image': string;
  'main': string;
  'section_one': string;
  'tour_details': string;
}
export const cssExports: CssExports;
export default cssExports;
