// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordions': string;
  'enroll': string;
  'line': string;
  'main': string;
  'timeline': string;
  'title': string;
  'title--dimmed': string;
  'tour_description': string;
  'tour_description__details': string;
  'tour_details__icon': string;
}
export const cssExports: CssExports;
export default cssExports;
