// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordions': string;
  'main': string;
  'title': string;
  'tour_description': string;
  'tour_description__details': string;
}
export const cssExports: CssExports;
export default cssExports;
