// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact_block': string;
  'contact_text': string;
  'content': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
