// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aaa': string;
  'btn': string;
  'btn__gray': string;
  'btn__light': string;
  'buttons': string;
  'gallery': string;
  'gallery_image': string;
  'image': string;
  'image_block': string;
  'legend': string;
  'main': string;
  'row': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
