// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'arrow__left': string;
  'arrow__right': string;
  'arrow_right': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
