// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow_left': string;
  'arrow_left_hidden': string;
  'arrow_right': string;
  'arrow_right_hidden': string;
  'content': string;
  'header': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
