// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'history': string;
  'image': string;
  'main': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
