// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'content': string;
  'content__img': string;
  'content__text': string;
  'main': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
