// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about_us': string;
  'button': string;
  'content': string;
  'content__img': string;
  'form': string;
  'main': string;
  'subtitle': string;
  'title': string;
  'vertical_line': string;
}
export const cssExports: CssExports;
export default cssExports;
