// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link__active': string;
  'logo': string;
  'main': string;
  'nav': string;
}
export const cssExports: CssExports;
export default cssExports;
