// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link__active': string;
  'link__block': string;
  'link__text': string;
  'logo': string;
  'logo__text': string;
  'main': string;
  'nav__left': string;
  'nav__right': string;
}
export const cssExports: CssExports;
export default cssExports;
