// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__logo': string;
  'link': string;
  'link__text': string;
  'link__text--active': string;
  'nav': string;
  'nav__left': string;
  'nav__right': string;
}
export const cssExports: CssExports;
export default cssExports;
