// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check': string;
  'header': string;
  'header__logo': string;
  'header__menu': string;
  'language_dropdown': string;
  'link': string;
  'link__text': string;
  'link__text--active': string;
  'menu_bar': string;
  'menu_bar__header': string;
  'menu_bar__items': string;
  'nav': string;
  'nav_left': string;
  'nav_toggle': string;
  'nav_toggle__bar': string;
  'nav_toggle__bar--short': string;
  'x': string;
}
export const cssExports: CssExports;
export default cssExports;
