// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'content__subtitle': string;
  'content__title': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
