// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact': string;
  'contact__icon': string;
  'contact__text': string;
  'contacts': string;
  'email__icon': string;
  'flex': string;
  'form': string;
  'form__title': string;
  'input_phone__container': string;
  'input_phone__country_btn': string;
  'input_phone__input': string;
  'label': string;
  'main': string;
  'phone__icon': string;
  'row': string;
  'row_three': string;
  'row_two_elements': string;
  'send_btn__container': string;
  'test_block': string;
  'text_copy': string;
}
export const cssExports: CssExports;
export default cssExports;
