// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contacts__container': string;
  'contacts__email': string;
  'contacts__email_icon': string;
  'contacts__email_text': string;
  'contacts__location': string;
  'contacts__location_icon': string;
  'contacts__location_text': string;
  'contacts__phone': string;
  'contacts__phone_icon': string;
  'contacts__phone_text': string;
  'form_container': string;
  'form_title': string;
  'input': string;
  'input_phone': string;
  'input_phone__country_btn': string;
  'main': string;
  'map__container': string;
  'row': string;
  'send_btn__container': string;
}
export const cssExports: CssExports;
export default cssExports;
