// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'custom_radios': string;
  'form_container': string;
  'form_title': string;
  'input': string;
  'input_phone': string;
  'input_phone__country_btn': string;
  'main': string;
  'map_container': string;
  'no': string;
  'row': string;
  'send_btn__container': string;
  'yes': string;
}
export const cssExports: CssExports;
export default cssExports;
