// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn__minus': string;
  'btn__plus': string;
  'input': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
