// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'day_description': string;
  'day_gallery': string;
  'day_number': string;
  'left_arrow': string;
  'movedown': string;
  'moveline': string;
  'program_time': string;
  'right': string;
  'right_arrow': string;
  'timeline': string;
  'tour_day': string;
}
export const cssExports: CssExports;
export default cssExports;
