// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel__image': string;
  'container': string;
  'day': string;
  'left_container': string;
  'left_container_arrow': string;
  'movedown': string;
  'moveline': string;
  'right_container': string;
  'right_container_arrow': string;
  'text_box': string;
  'timeline': string;
}
export const cssExports: CssExports;
export default cssExports;
