// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'info__icon': string;
  'info__text': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
