// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main': string;
  'tour_description': string;
  'tour_description__button': string;
  'tour_description__duration': string;
  'tour_description__subtitle': string;
  'tour_description__title': string;
  'tour_image': string;
}
export const cssExports: CssExports;
export default cssExports;
