// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'image_block__current': string;
  'main': string;
  'read_more': string;
  'tour': string;
  'tour--scale': string;
  'tour__heading': string;
  'tour__image': string;
}
export const cssExports: CssExports;
export default cssExports;
