// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'image': string;
  'image_block': string;
  'image_block__current': string;
  'main': string;
  'read_more': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
