// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel': string;
  'carousel__image': string;
  'carousel__legend': string;
  'contact_us': string;
  'contact_us__button': string;
  'contact_us__subtitle': string;
  'contact_us__title': string;
  'gallery': string;
  'gallery_image': string;
  'main': string;
  'modal_history': string;
  'modal_image': string;
  'modal_main': string;
  'modal_text': string;
  'modal_title': string;
  'place': string;
  'place__image': string;
  'place__legend': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
