// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion_button': string;
  'accordion_button--error': string;
  'accordion_content': string;
  'accordion_header': string;
  'accordion_header_input': string;
}
export const cssExports: CssExports;
export default cssExports;
