// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion__content': string;
  'accordion__input': string;
  'accordion__label': string;
  'accordion__toggle': string;
  'accordion__toggle--error': string;
}
export const cssExports: CssExports;
export default cssExports;
