// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date_input': string;
  'date_input--error': string;
  'date_input-error': string;
}
export const cssExports: CssExports;
export default cssExports;
